services:
  - type: web
    name: sms-spam-classifier
    env: python
    buildCommand: |
      mkdir -p nltk_data
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt', download_dir='nltk_data'); nltk.download('stopwords', download_dir='nltk_data'); nltk.download('punkt_tab', download_dir='nltk_data')"
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
    healthCheckPath: /health 